name: Sync Submodules 4 times a day

on:
  schedule:
    - cron: '0 */6 * * *'  # runs every 6 hours UTC
  workflow_dispatch:

jobs:
  submodule-sync:
    name: Submodule update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo with submodules (using PAT)
        uses: actions/checkout@v4
        with:
          repository: rccyx/dotfiles
          token: ${{ secrets.GH_PAT }}
          submodules: recursive

      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Pull latest commits for all submodules
        run: |
          git submodule foreach --recursive '
            echo "Updating $name..."
            git checkout main || git checkout master || exit 1
            git pull origin HEAD
          '

      - name: Commit & push updates
        run: |
          git add .
          git commit -m "auto updated submodule references" || echo "No changes"
          git push || echo "No push needed"

